<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=11"/>
<meta name="generator" content="Doxygen 1.16.1"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>ccdb: Allocator Struct Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<script type="text/javascript" src="clipboard.js"></script>
<link href="navtree.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="navtreedata.js"></script>
<script type="text/javascript" src="navtree.js"></script>
<script type="text/javascript" src="cookie.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr id="projectrow">
  <td id="projectalign">
   <div id="projectname">ccdb<span id="projectnumber">&#160;1.45.12</span>
   </div>
   <div id="projectbrief">C/C++ Static Template</div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.16.1 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search/",'.html');
</script>
<script type="text/javascript">
$(function() { codefold.init(); });
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('',true,false,'search.php','Search',true);
  $(function() { init_search(); });
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div id="side-nav" class="ui-resizable side-nav-resizable">
  <div id="nav-tree">
    <div id="nav-tree-contents">
      <div id="nav-sync" class="sync"></div>
    </div>
  </div>
  <div id="splitbar" style="-moz-user-select:none;" 
       class="ui-resizable-handle">
  </div>
</div>
<script type="text/javascript">
$(function(){initNavTree('struct_allocator.html','','struct_allocator-members'); });
</script>
<div id="container">
<div id="doc-content">
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<div id="MSearchResults">
<div class="SRPage">
<div id="SRIndex">
<div id="SRResults"></div>
<div class="SRStatus" id="Loading">Loading...</div>
<div class="SRStatus" id="Searching">Searching...</div>
<div class="SRStatus" id="NoMatches">No Matches</div>
</div>
</div>
</div>
</div>

<div class="header">
  <div class="headertitle"><div class="title">Allocator Struct Reference<div class="ingroups"><a class="el" href="group__allocator__interface.html">Generic Allocator Interface</a></div></div></div>
</div><!--header-->
<div class="contents">

<p>A generic allocator backed by function pointers (vtable).  
 <a href="#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="mem__allocator_8h_source.html">mem_allocator.h</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 id="header-pub-attribs" class="groupheader"><a id="pub-attribs" name="pub-attribs"></a>
Public Attributes</h2></td></tr>
<tr class="memitem:a85bda7718e8e0dbe5ebc904b61dfbb36" id="r_a85bda7718e8e0dbe5ebc904b61dfbb36"><td class="memItemLeft">void *&#160;</td><td class="memItemRight"><a class="el" href="#a85bda7718e8e0dbe5ebc904b61dfbb36">ctx</a></td></tr>
<tr class="memitem:a1babc9f08e6879d2fdf679f1d67fc4b3" id="r_a1babc9f08e6879d2fdf679f1d67fc4b3"><td class="memItemLeft"><a class="el" href="group__allocator__interface.html#gaa9711913378a4067a9b978c3e473d21f">AllocFn</a>&#160;</td><td class="memItemRight"><a class="el" href="#a1babc9f08e6879d2fdf679f1d67fc4b3">alloc</a></td></tr>
<tr class="memitem:ae3aedd6e0186104f9746d37ff6d6193d" id="r_ae3aedd6e0186104f9746d37ff6d6193d"><td class="memItemLeft"><a class="el" href="group__allocator__interface.html#gab2c9f2d8a22b358e44fd58a4f4c82fb7">FreeFn</a>&#160;</td><td class="memItemRight"><a class="el" href="#ae3aedd6e0186104f9746d37ff6d6193d">free</a></td></tr>
<tr class="memitem:aa097a1634ca1d314c8ace964edb11c41" id="r_aa097a1634ca1d314c8ace964edb11c41"><td class="memItemLeft"><a class="el" href="group__allocator__interface.html#ga93cd308ca3c0baf92642c3a365221460">ReallocFn</a>&#160;</td><td class="memItemRight"><a class="el" href="#aa097a1634ca1d314c8ace964edb11c41">realloc</a></td></tr>
</table>
<a name="details" id="details"></a><h2 id="header-details" class="groupheader">Detailed Description</h2>
<div class="textblock"><p>A generic allocator backed by function pointers (vtable). </p>
<p>Pass by pointer to any function that needs to allocate memory without caring about the concrete allocator type.</p>
<dl class="section note"><dt>Note</dt><dd>Passing by pointer is preferred over by value to allow the callee to observe state changes (e.g., arena pos advancing). </dd></dl>

<p class="definition">Definition at line <a class="el" href="mem__allocator_8h_source.html#l00108">108</a> of file <a class="el" href="mem__allocator_8h_source.html">mem_allocator.h</a>.</p>
</div><a name="doc-variable-members" id="doc-variable-members"></a><h2 id="header-doc-variable-members" class="groupheader">Member Data Documentation</h2>
<a id="a1babc9f08e6879d2fdf679f1d67fc4b3" name="a1babc9f08e6879d2fdf679f1d67fc4b3"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a1babc9f08e6879d2fdf679f1d67fc4b3">&#9670;&#160;</a></span>alloc</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="group__allocator__interface.html#gaa9711913378a4067a9b978c3e473d21f">AllocFn</a> Allocator::alloc</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Allocation function. Must not be NULL. </p>

<p class="definition">Definition at line <a class="el" href="mem__allocator_8h_source.html#l00110">110</a> of file <a class="el" href="mem__allocator_8h_source.html">mem_allocator.h</a>.</p>

</div>
</div>
<a id="a85bda7718e8e0dbe5ebc904b61dfbb36" name="a85bda7718e8e0dbe5ebc904b61dfbb36"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a85bda7718e8e0dbe5ebc904b61dfbb36">&#9670;&#160;</a></span>ctx</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void* Allocator::ctx</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Opaque context passed to every function pointer. </p>

<p class="definition">Definition at line <a class="el" href="mem__allocator_8h_source.html#l00109">109</a> of file <a class="el" href="mem__allocator_8h_source.html">mem_allocator.h</a>.</p>

</div>
</div>
<a id="ae3aedd6e0186104f9746d37ff6d6193d" name="ae3aedd6e0186104f9746d37ff6d6193d"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ae3aedd6e0186104f9746d37ff6d6193d">&#9670;&#160;</a></span>free</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="group__allocator__interface.html#gab2c9f2d8a22b358e44fd58a4f4c82fb7">FreeFn</a> Allocator::free</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Free function. May be NULL for arena allocators. </p>

<p class="definition">Definition at line <a class="el" href="mem__allocator_8h_source.html#l00111">111</a> of file <a class="el" href="mem__allocator_8h_source.html">mem_allocator.h</a>.</p>

</div>
</div>
<a id="aa097a1634ca1d314c8ace964edb11c41" name="aa097a1634ca1d314c8ace964edb11c41"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aa097a1634ca1d314c8ace964edb11c41">&#9670;&#160;</a></span>realloc</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="group__allocator__interface.html#ga93cd308ca3c0baf92642c3a365221460">ReallocFn</a> Allocator::realloc</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Realloc function. May be NULL if not supported. </p>

<p class="definition">Definition at line <a class="el" href="mem__allocator_8h_source.html#l00112">112</a> of file <a class="el" href="mem__allocator_8h_source.html">mem_allocator.h</a>.</p>

</div>
</div>
<hr/>The documentation for this struct was generated from the following file:<ul>
<li>include/memory/<a class="el" href="mem__allocator_8h_source.html">mem_allocator.h</a></li>
</ul>
</div><!-- contents -->
</div><!-- doc-content -->
<div id="page-nav" class="page-nav-panel">
<div id="page-nav-resize-handle"></div>
<div id="page-nav-tree">
<div id="page-nav-contents">
</div><!-- page-nav-contents -->
</div><!-- page-nav-tree -->
</div><!-- page-nav -->
</div><!-- container -->
<!-- start footer part -->
<div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
  <ul>
    <li class="navelem"><a href="struct_allocator.html">Allocator</a></li>
    <li class="footer">Generated by <a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.16.1 </li>
  </ul>
</div>
</body>
</html>
